// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {transfer} from '../models';
import {config} from '../models';

export function CancelTransfer(arg1:string,arg2:number):Promise<void>;

export function ClearCompletedTransfers(arg1:string):Promise<void>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<string>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DisconnectAll():Promise<void>;

export function DisconnectSession(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetActiveTunnels(arg1:string):Promise<Array<main.TunnelInfo>>;

export function GetLocalWD():Promise<string>;

export function GetSessionPassword(arg1:string):Promise<string>;

export function GetTransfers(arg1:string):Promise<Array<transfer.TransferItem>>;

export function GoUp(arg1:string,arg2:string):Promise<string>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<main.FileItem>>;

export function ListLocalFiles(arg1:string):Promise<Array<main.FileItem>>;

export function LoadSessions():Promise<Array<config.Session>>;

export function RenameFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function SelectSavePath(arg1:string):Promise<string>;

export function SelectUploadFile():Promise<string>;

export function StartLocalForward(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function StopLocalForward(arg1:string,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
