// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer(arg1, arg2) {
  return window['go']['main']['App']['CancelTransfer'](arg1, arg2);
}

export function ClearCompletedTransfers(arg1) {
  return window['go']['main']['App']['ClearCompletedTransfers'](arg1);
}

export function Connect(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteRemoteFile'](arg1, arg2);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DisconnectAll() {
  return window['go']['main']['App']['DisconnectAll']();
}

export function DisconnectSession(arg1) {
  return window['go']['main']['App']['DisconnectSession'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function GetActiveTunnels(arg1) {
  return window['go']['main']['App']['GetActiveTunnels'](arg1);
}

export function GetLocalWD() {
  return window['go']['main']['App']['GetLocalWD']();
}

export function GetSessionPassword(arg1) {
  return window['go']['main']['App']['GetSessionPassword'](arg1);
}

export function GetTransfers(arg1) {
  return window['go']['main']['App']['GetTransfers'](arg1);
}

export function GoUp(arg1, arg2) {
  return window['go']['main']['App']['GoUp'](arg1, arg2);
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListLocalFiles(arg1) {
  return window['go']['main']['App']['ListLocalFiles'](arg1);
}

export function LoadSessions() {
  return window['go']['main']['App']['LoadSessions']();
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}

export function SelectUploadFile() {
  return window['go']['main']['App']['SelectUploadFile']();
}

export function StartLocalForward(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartLocalForward'](arg1, arg2, arg3, arg4);
}

export function StopLocalForward(arg1, arg2) {
  return window['go']['main']['App']['StopLocalForward'](arg1, arg2);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
